// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:4e7e3ebd-4992-43b0-a8eb-781fc1294600",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_UV1TxG2GG",
    "aws_user_pools_web_client_id": "41ca7s1medtt2h41tpqiom2tet"
};


export default awsmobile;
